CREATE TABLE Person (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credentials varchar(100) NOT NULL UNIQUE,
    birth_date int NOT NULL
);

CREATE TABLE Book (
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    publication_year int NOT NULL,
    user_id int REFERENCES Person(user_id) ON DELETE SET NULL,
    taken_at TIMESTAMP
);